runtime:
  log:
    failure_level: warn
git:
  # ensure_git_suffix: false # Enable if necessary -- some git services donâ€™t recognize the URL if it contains the .git extension.
  fetch_concurrency: 10

site:
  title: DataStax RAGStack Docs
  start_page: ragstack::index.adoc
  robots: disallow

content:
  # branches: main # Sources default to this branch if none are specified.
  sources:
  - url: https://github.com/datastax/ragstack-ai.git
    branches: add-docs # Override the default branch for this source.
    start_path: docs

antora:
  extensions:
  - '@antora/collector-extension'
  - lib/tailwind-processor.js

asciidoc:
  extensions:
  - '@asciidoctor/tabs'
  - lib/remote-include-processor.js
  - lib/svg-macro.js
  - asciidoctor-kroki
  - asciidoctor-external-callout
  attributes:
    # BUILT-IN ATTRIBUTES
    allow-uri-read: '' # this has no effect in antora, but does help development in Intellij
    experimental: ''
    idprefix: ''
    idseparator: '-'
    # kroki-fetch-diagram: true
    # kroki-server-url:
    max-include-depth: 10
    page-toclevels: 2@
    sectlinks: ''
    tabs-sync-option: ''
    table-caption: false
    figure-caption: false
    xrefstyle: short
    # CUSTOM ATTRIBUTES
    company: 'DataStax'
    astra_db: 'Astra DB'
    astra_stream: 'Astra Streaming'
    astra_ui: 'Astra Portal'
    support_url: 'https://support.datastax.com'
    glossary-url: 'https://docs.datastax.com/en/glossary/docs/index.html#'
    external-link-icon: '&#x2197;'
    examples-repo: 'https://github.com/mendonk/ragstack-notebooks'
urls:
  # redirect_facility: httpd
  latest_version_segment_strategy: redirect:from
  latest_version_segment: 'latest'

ui:
  bundle:
    url: https://github.com/riptano/docs-ui/releases/latest/download/ui-bundle.zip
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  # supplemental_files: supplemental-ui

output:
  dir: 'build/site'
