name: LLamaIndex dev branch
on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 */2 * * *'
  pull_request:
    paths:
      - '.github/**'
      - 'ragstack-e2e-tests/**'
    branches:
      - main

jobs:
  llamaindex-tests:
    name: "Tests using Llama-Index main branch (${{ matrix.name }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Astra DEV
            skip: "${{ github.event_name == 'pull_request' }}"
            type: "astradb"
            needs_astra_setup: true
            astra_token_secret: E2E_TESTS_ASTRA_DEV_DB_TOKEN
            env: DEV
            region: us-west-2
            cloud: aws
            testspace_space: "RAGStack test suite - LLamaIndex dev - AstraDB"

          - name: DSE
            skip: false
            type: "local-cassandra"
            needs_astra_setup: false
            astra_token_secret: ""
            env: ""
            region: ""
            cloud: ""
            testspace_space: "RAGStack test suite - LLamaIndex dev - DSE"
    steps:
      - name: Check out the repo
        if: !matrix.skip
        uses: actions/checkout@v3

      - name: 'Setup: Python 3.11'
        if: !matrix.skip
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        if: !matrix.skip
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Setup AstraDB
        uses: ./.github/actions/setup-astra-db
        id: astra-db
        if: matrix.needs_astra_setup && !matrix.skip
        with:
          astra-token: ${{ secrets[matrix.astra_token_secret] }}
          db-name: ${{ github.run_id }}-${{ github.run_attempt }}
          env: ${{ matrix.env }}
          region: ${{ matrix.region }}
          cloud: ${{ matrix.cloud }}

      - name: Run E2E tests
        id: e2e-tests
        if: !matrix.skip
        env:
          VECTOR_DATABASE_TYPE: "${{ matrix.type }}"
          ASTRA_DB_TOKEN: "${{ secrets[matrix.astra_token_secret] }}"
          ASTRA_DB_ENDPOINT: "${{ steps.astra-db.outputs.db_endpoint }}"
          ASTRA_DB_ID: "${{ steps.astra-db.outputs.db_id }}"
          ASTRA_DB_ENV: "${{ matrix.env }}"
          OPEN_AI_KEY: "${{ secrets.E2E_TESTS_OPEN_AI_KEY }}"
          AZURE_OPEN_AI_KEY: "${{ secrets.E2E_TESTS_AZURE_OPEN_AI_KEY }}"
          AZURE_OPEN_AI_ENDPOINT: "${{ secrets.E2E_TESTS_AZURE_OPEN_AI_ENDPOINT }}"
          AZURE_BLOB_STORAGE_CONNECTION_STRING: "${{ secrets.E2E_TESTS_AZURE_BLOB_STORAGE_CONNECTION_STRING }}"
          GCLOUD_ACCOUNT_KEY_JSON: "${{ secrets.E2E_TESTS_GCLOUD_ACCOUNT_KEY_JSON }}"
          GOOGLE_API_KEY: "${{ secrets.E2E_TESTS_GOOGLE_API_KEY }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.E2E_TESTS_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.E2E_TESTS_AWS_SECRET_ACCESS_KEY }}"
          BEDROCK_AWS_REGION: "${{ secrets.E2E_TESTS_BEDROCK_AWS_REGION }}"
          HUGGINGFACE_HUB_KEY: "${{ secrets.E2E_TESTS_HUGGINGFACE_HUB_KEY }}"
          NVIDIA_API_KEY: "${{ secrets.E2E_TESTS_NVIDIA_API_KEY }}"
          LANGCHAIN_API_KEY: "${{ secrets.E2E_TESTS_LANGCHAIN_API_KEY }}"
        run: |
          source scripts/ci-common-env.sh
          tox -c ragstack-e2e-tests -e llamaindex

      - name: Dump report on Github Summary
        if: always() && !matrix.skip
        uses: ./.github/actions/add-report-to-github-summary

      - name: Compute commit URL
        if: always() && !matrix.skip
        id: commit-ref
        run: echo "commit-ref=$(grep resolved_reference ragstack-e2e-tests/poetry.lock | awk -F'"' '{print $2}' | head -1)" >> $GITHUB_OUTPUT

      - name: Slack deploy report
        if: always() && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && !matrix.skip
        uses: ./.github/actions/deploy-slack-report
        with:
          from-report-file: "ragstack-e2e-tests/failed-tests-report.txt"
          type: "Tests using Llama-Index main branch (${{ matrix.name }})"
          outcome: ${{ steps.e2e-tests.outcome }}
          commit-url: "https://github.com/run-llama/llama_index/commits/${{ steps.commit-ref.outputs.commit-ref }}"
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Testspace deploy report
        uses: ./.github/actions/deploy-testspace-report
        if: always() && matrix.testspace_space != '' && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && !matrix.skip
        with:
          token: ${{ secrets.TESTSPACE_TOKEN }}
          report-file: ragstack-e2e-tests/results.xml
          space: ${{ matrix.testspace_space }}

      - name: Cleanup AstraDB
        uses: ./.github/actions/cleanup-astra-db
        if: always() && matrix.needs_astra_setup && !matrix.skip
        with:
          astra-token: ${{ secrets[matrix.astra_token_secret] }}
          db-name: ${{ github.run_id }}-${{ github.run_attempt }}
          env: ${{ matrix.env }}
